name: Compilation

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ${{ matrix.os[0] }}
    strategy:
      matrix:
        os: [
          [macos-latest, arm64, bash],
          [macos-15-intel, x86_64, bash],
          [ubuntu-latest, x86_64, bash],
          [windows-latest, x86_64, msys2]
        ]
        debug: [RelWithDebInfo]
      fail-fast: false
    defaults:
     run:
      shell: ${{ matrix.os[2] }} {0}

    steps:
    - uses: actions/checkout@v4

    - name: Install Ubuntu packages
      if: matrix.os[0] == 'ubuntu-latest'
      run: |
        sudo apt-get -y update
        sudo apt-get -y install cmake

    - name: Install macOS packages (brew)
      if: startsWith(matrix.os[0], 'macos-')
      run: |
        brew update
        brew install cmake

    # MacPorts path not used in current matrix; keep commented sample if needed

    - name: Install MSYS2 packages
      if: matrix.os[0] == 'windows-latest'
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW32
        install: |
          base-devel git
          mingw-w64-i686-gcc mingw-w64-i686-make mingw-w64-i686-cmake
          mingw-w64-i686-libgnurx
        update: true

    - name: Compile MASP
      run: |
        export PS2DEV=$PWD/ps2dev
        export PATH="$PS2DEV/bin:$PATH"
        cmake -B build-cmake -DCMAKE_BUILD_TYPE=${{ matrix.debug }} -DCMAKE_INSTALL_PREFIX=$PS2DEV
        cmake --build build-cmake --config ${{ matrix.debug }}
        cmake --install build-cmake --prefix $PS2DEV

    - name: Test MASP
      run: |
        export PS2DEV=$PWD/ps2dev
        export PATH="$PS2DEV/bin:$PATH"
        masp -p -s -c ';' -o test/vu1Triangle.vcl_masp test/vu1Triangle.vcl

    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v4
      with:
        name: masp-${{ matrix.debug }}-${{ matrix.os[0] }}-${{ matrix.os[1] }}
        path: build-cmake/src/masp