name: Compilation

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ${{ matrix.os[0] }}
    strategy:
      matrix:
        os: [
          [macos-latest, arm64, bash],
          [macos-15-intel, x86_64, bash],
        ]
        debug: [Debug, RelWithDebInfo]
      fail-fast: false
    defaults:
     run:
      shell: ${{ matrix.os[2] }} {0}

    steps:
    - uses: actions/checkout@v4

    - name: Install MSYS2 packages
      if: matrix.os[0] == 'windows-latest'
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW32
        install: |
          base-devel mingw-w64-i686-gcc mingw-w64-i686-cmake
        update: true

    - name: Compile MASP
      run: |
        cmake -B build-cmake -DCMAKE_BUILD_TYPE=${{ matrix.debug }} -DCMAKE_INSTALL_PREFIX=$HOME/.local
        cmake --build build-cmake --config ${{ matrix.debug }}
        cmake --install build-cmake -v

    - name: Add install dir to PATH
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Test MASP
      run: |
        which masp
        masp --version

    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v4
      with:
        name: masp-${{ matrix.debug }}-${{ matrix.os[0] }}-${{ matrix.os[1] }}
        path: build-cmake/src/masp